// app-svelte/src/views/Landing.svelte
<script lang="ts">
  import SvIcon from 'src/components/lib/SVIcon.svelte';
  import { useUserStore } from 'src/store/user';
  import { setToken } from 'src/utils/api';
  import { getUserData, setUUID, tokenWatcher } from 'src/utils/authState';
  import { onMount } from 'svelte';
  import { useLocation, useNavigate } from 'svelte-navigator';

  const navigate = useNavigate();
  const location = useLocation();
  const { setLogin } = useUserStore();

  const url = import.meta.env.VITE_API;

  function login(type: 'google' | 'fb') {
    switch (type) {
      case 'google':
        window.location.href = `${url}/auth/google/`;
        break;

      case 'fb':
        window.location.href = `${url}/auth/fb/`;
        break;

      default:
        break;
    }
  }

  function getSuccessToken() {
    const locationStr = $location.hash || $location.search;

    return locationStr.split('auth_success=')[1] || '';
  }

  async function catchRedirect() {
    const auth_success = getSuccessToken();

    if (!auth_success.length) return;

    setToken(auth_success);

    try {
      const data = await getUserData();

      localStorage.setItem('__token', data.refreshToken);
      setToken(data.accessToken);

      setLogin(data);
      setUUID();

      tokenWatcher(navigate);

      navigate('/home');
      // hideLoader();
    } catch (error) {
      console.log(error);
      // hideLoader();
    }
  }

  onMount(async () => await catchRedirect());
</script>

<div class="hero h-[calc(100vh-48px)]">
  <div class="flex-col justify-center hero-content lg:flex-row">
    <div class="text-center lg:text-left">
      <img src="/icon-144.png" class="block m-auto pb-3" alt="icon-72.png" />
      <div class="text-5xl font-bold text-center mb-2">Furikaeru</div>

      <p class="mb-5 text-lg text-justify">
        A small app to discuss retrospective while being Anonymous. Create public/private boards with a simple kanban
        board interface and realtime changes. Flexible, simple and free.
      </p>
    </div>
    <div class="card flex-shrink-0 w-full max-w-lg border border-primary ">
      <div class="card-body px-3 py-10">
        <div class="alert alert-info py-2">
          <div class="flex-1 space-x-2">
            <SvIcon icon="ion:information-circle" size="25px" />
            <div class="text-sm">
              You are currently in anonymous mode. You can still view/edit public boards. Login/signup to create a
              board.
            </div>
          </div>
        </div>

        <div class="text-center text-lg mt-5">Login with</div>

        <div class="flex justify-center space-x-2 mt-2  ">
          <button class="btn btn-secondary btn-md btn-square" on:click={() => login('google')}>
            <SvIcon icon="ion:logo-google" size="25px" />
          </button>

          <button class="btn btn-secondary btn-md btn-square" on:click={() => login('google')}>
            <SvIcon icon="ion:logo-facebook" size="25px" />
          </button>
        </div>

        <div class="text-sm text-center mt-6">To prevent spamming, only passwordless login is available.</div>
      </div>
    </div>
  </div>
</div>

// app/src/pages/Landing.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import Axios from 'axios';
import { useRoute, useRouter } from 'vue-router';
import { useUser } from 'src/store/user';
import type { UserResponse } from 'src/store/user';
import FBanner from 'src/components/lib/FBanner.vue';
import AppFooter from 'src/components/App/Footer.vue';
import FButton from 'src/components/lib/FButton.vue';
import { Head } from '@vueuse/head';

const { setLogin, showLoader, hideLoader } = useUser();

const url = import.meta.env.VITE_API;
const { query } = useRoute();
const { push } = useRouter();

function login(type: 'google' | 'fb') {
  switch (type) {
    case 'google':
      window.location.href = `${url}/auth/google/`;
      break;

    case 'fb':
      window.location.href = `${url}/auth/fb/`;
      break;

    default:
      break;
  }
}

async function catchRedirect() {
  if (!Object.keys(query)) return;
  if (!query.auth_success) return;
  showLoader();
  const { auth_success } = query;
  try {
    const { data } = await Axios.get<UserResponse>('/auth/user', {
      baseURL: import.meta.env.VITE_API,
      headers: {
        Authorization: `Bearer ${auth_success}`,
      },
    });

    setLogin({ ...data });
    await push('/user');
    hideLoader();
  } catch (error) {
    console.log(error);
    hideLoader();
  }
}

onMounted(async () => {
  await catchRedirect();
});
</script>
<template>
  <div>
    <Head>
      <title>Login/ Signup | Furikaeru</title>
    </Head>

    <div class="mt-20 flex flex-row justify-center">
      <div class="login sm:w-4/5 lg:w-2/5 w-full">
        <div class="login_card bg-gray-100 px-10 pt-5 p-b-10 rounded-xl">
          <img src="/icon-72.png" class="block m-auto pb-3" alt="icon-48.png" />
          <div class="grid grid-cols-1 gap-3 text-center">
            <div class="text-xl mb-4">
              <div>
                Welcome to
                <b class="text-cyan-500">Furikaeru</b>
                !
              </div>
              <f-banner
                noicon
                text="Furikaeru is in active development. Bugs and frequent changes are expected."
                class="my-2"
              />
            </div>

            <div class="pb-3">
              <f-banner class="mb-2" noicon>
                You are currently in
                <b class="text-cyan-600">anonymous</b>
                &nbsp;mode.
              </f-banner>
              <div class="text-sm text-gray-500">
                You can still view/edit public boards. Login/signup to create a board.
              </div>
            </div>
            <div class="text-xl">Login with</div>
            <div class="flex space-x-2 justify-center">
              <f-button icon="ion:logo-google" size="25px" class="!px-2" @click="login('google')" />
              <f-button icon="ion:logo-facebook" size="25px" class="!px-2" @click="login('fb')" />
            </div>
            <div class="text-sm text-gray-500">To prevent spamming, only passwordless login is available.</div>
          </div>
        </div>
      </div>
    </div>
    <app-footer />
  </div>
</template>
