// app/src/App.vue
<script setup lang="ts">
import Navbar from 'src/components/App/Navbar.vue';
import { authState } from 'src/utils/authState';
import { registerToken } from 'src/utils/helpers';

authState();
registerToken();
</script>
<template>
  <div>
    <Navbar />
    <div class="max-w-7xl mx-auto p-2">
      <router-view />
    </div>
  </div>
</template>

// app-svelte/src/App.svelte
<script lang="ts">
  import { Router } from 'svelte-navigator';
  import Navbar from './components/app/navbar.svelte';
  import { refreshUser } from './utils/authState';
  import Wrap from './Wrap.svelte';

  export let url = '';

  const { isAuth } = refreshUser();
</script>

<main>
  {#if !$isAuth}
    <Navbar />
  {/if}

  <Router {url}>
    <Wrap />
  </Router>
</main>
